server:
  port: ${APPLICATION_SERVICE_PORT:8084}
spring:
  application:
    name: application-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    mongodb:
      uri: ${APPLICATION_MONGODB_URI:${MONGODB_URI:mongodb://localhost:27017/careerlink_application}}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
management:
  endpoints:
    web:
      exposure:
        include: health,info
